### PR TITLE
Make bundle loadable in non-es6 browsers

### PR DESCRIPTION
**Pull request by xdumaine**
The currently bundle pulls in es6 modules which don't get transformed. If you Then use that on a site that gets loaded in non-es6 browsers, you bring down the house. This updates the build/bundle to support those.

### CODE REVIEW

**Comment by xdumaine** [comment]
And before you say it, @fippo I know you'd rather not have the bundle at all.

**Comment by fippo** [comment]
haha. Is this caused by a version of adapter.js that was assuming es6?

**Comment by xdumaine** [comment]
@fippo yep, that's exactly what it was.

**Comment by xdumaine** [comment]
Travis is doing something weird, and timing out builds. Any opposition to merge with minor version bump?

**Comment by fippo** [comment]
kicked travis, merge if this doesn't help.

**Comment by xdumaine** [comment]
Published as 5.2.0

**Pull request merged**
