### PR TITLE
Remove webrtcsupport

### PR DESCRIPTION
**Pull request by xdumaine**
I noticed that including RTCPeerConnection was including webrtcsupport, but was no longer used. I also added a jshint rule for unused variable warnings, and fixed all resulting errors.

### CODE REVIEW

**Comment by xdumaine** [comment]
@fippo

**Comment by fippo** [comment]
LGTM

**Comment by xdumaine** [comment]
(I don't have merge permission here)

**Comment by fippo** [comment]
let me add you to npm as well...

**Comment by fippo** [comment]
done, happy bumping (patch i think)

**Pull request merged**
