### PR TITLE
Using the browserDetails from adapter to get browser type

### PR DESCRIPTION
**Pull request by Kenny-House**
Since bumping to adapter 1.0, all of the browser checks evaluate to false because rtcpeerconnection is still using the old `webrtcDetectedBrowser` property:

https://github.com/webrtc/adapter/blob/d294abacd7098235873c1b90e7b992fff247bf74/src/js/adapter_core.js#L16

Adapter now has a `browserDetails.browser` property instead for the browser type.

### CODE REVIEW

**Comment by xdumaine** [comment]
Hey thanks! @Kenny-House could you revert the change to the bundle file? We'll update that after merging. Other than that, LGTM.

**Comment by Kenny-House** [comment]
Sure thing, sorry about that, I wasn't quite sure how you guys handle the build on that.

I went ahead and pushed up a commit reverting the build.js to the previous version.

**Comment by xdumaine** [comment]
@fippo?

**Comment by fippo** [comment]
@legastero already volunteeered. h/t kenny :-)

**Comment by legastero** [comment]
LGTM, merging

**Pull request merged**
