### PR TITLE
new line compatibility fix

### PR DESCRIPTION
**Pull request by itsazzad**

### CODE REVIEW

**Comment by tgabi333** [comment]
in which cases fix the processing?

**Comment by itsazzad** [comment]
https://github.com/otalk/RTCPeerConnection/pull/94/files
sdp incoming from mobile device was not parsing at all.
Solution: https://stackoverflow.com/a/21895354/540144
Similar thing I found in here.

**Comment by fippo** [comment]
https://tools.ietf.org/html/rfc4566#section-5 says
```
 The sequence
   CRLF (0x0d0a) is used to end a record, although parsers SHOULD be
   tolerant and also accept records terminated with a single newline
   character.
```

@legastero how is ripping out SJJ going?

**Comment by itsazzad** [comment]
Is that going to be merged soon?

**Comment by tgabi333** [comment]
@fippo @xdumaine could you please release it to npm (or add me as a collaborator there)

**Comment by xdumaine** [comment]
Released as v8.2.0. 

@tgabi333 is your npm username the same as github, or something else?

**Comment by tgabi333** [comment]
yes, thanks

**Pull request merged**
