### PR TITLE
don't blow up if getRemoteStreams is not available

### PR DESCRIPTION
**Pull request by xdumaine**
same as getLocalStreams.

Will just be a patch.

### CODE REVIEW

**Comment by fippo** [comment]
where is it not available, safari?

**Comment by xdumaine** [comment]
Yep, safari.

**Comment by fippo** [comment]
shim it in adapter?

**Comment by fippo** [comment]
arguably i would recommend getReceivers where possible ;-)

**Comment by xdumaine** [comment]
@fippo The reason to add it here is that this lib proxied it before. A major version bump will just remove it and switch to getReceivers. Don't think we need to shim it in safari since ideally it'll just phased out, right?

**Comment by fippo** [comment]
i hope so but am not very optimistic (for the spec in general)

**Pull request merged**
