### PR TITLE
update to webrtc-adapter v1.0

### PR DESCRIPTION
**Pull request by tgabi333**
jshint devdependencies added

small improvements to travis

### CODE REVIEW

**Comment by tgabi333** [comment]
also fixes https://github.com/otalk/RTCPeerConnection/issues/62

**Comment by fippo** [comment]
hey @tgabi333 -- interested in being able to merge this (and the other stuff) yourself? Both @legastero and @xdumaine are +1 and you have been helping out for a while so...

**Comment by tgabi333** [comment]
@fippo, @legastero, @xdumaine  Thank you all, it means a great honor for me. i would gladly join this repo.

**Comment by fippo** [comment]
invite sent. Welcome!

We'll do the npm publish stuff gradually, lots of modules. Until then, feel free to ping me, @legastero or @xdumaine when something needs publishing.

changes LGTM, go ahead with merging

**Comment by tgabi333** [comment]
Thank you very much guys!

**Comment by fippo** [comment]
argh... did things in the wrong order. Published 4.1.1 with old traceablepeerconnection, will bump patch in a bit.

one thing for the future: we typically update the bundle after merging -- avoids merge conflicts.

**Comment by fippo** [comment]
and 4.1.2 published

**Pull request merged**
