### PR TITLE
Don't bind to addStream if it doesn't exist (safari)

### PR DESCRIPTION
**Pull request by xdumaine**

### CODE REVIEW

**Comment by fippo** [comment]
wait, dont we have a shim from adapter?

**Comment by xdumaine** [comment]
This is kind of a mess... I shimmed removeStream in here, apparently. The problem is adapter is shimming toward spec, and addStream and removeStream are not in spec, they're legacy, so they'd be shimmed outside of adapter if we want to keep them.

**Comment by xdumaine** [comment]
Or maybe I'm crazy and just need to update my adapter version...

**Comment by fippo** [comment]
adapter shims toward spec while not (intentionally) breaking legacy. So this should still work...

**Comment by xdumaine** [comment]
Yeah, upgraded and still not seeing addStream. Odd...

**Comment by Gazfay** [comment]
Any update?

**Comment by fippo** [comment]
What is the issue? Note that this package is generally supposed to be installed alongside https://www.npmjs.com/package/webrtc-adapter

**Pull request closed without merging**
